import type {LayerCategory} from "@/types/network"

// 预定义的层类型
export const layerTypes: LayerCategory[] = [
    {
        category: "Input",
        layers: [
            {
                type: "Input",
                label: "Input",
                iconName: "Layers",
                color: "text-blue-600",
                params: {in_features: 784, out_features: 128, bias: true,device: "cpu", dtype: "float32"},
                inputShape: "None",
                outputShape: "[Out]",
            },
        ],
    },
    {
        category: "Dense Layers",
        layers: [
            {
                type: "Linear",
                label: "Linear",
                iconName: "Brain",
                color: "text-purple-600",
                params: {in_features: 784, out_features: 128, bias: true,device: "cpu", dtype: "float32"},
                inputShape: "[784]",
                outputShape: "[128]",
            },
            {
                type: "Dropout",
                label: "Dropout",
                iconName: "Layers",
                color: "text-orange-600",
                params: {p: 0.5, inplace: false},
                inputShape: "[C]",
                outputShape: "[C]",
            },
        ],
    },
    {
        category: "Convolutional Layers",
        layers: [
            {
                type: "Conv1d",
                label: "Conv1D",
                iconName: "Layers",
                color: "text-blue-600",
                params: {in_channels: 4, out_channels: 64, kernel_size: 3, stride: 1, padding: 0, dilation: 1, groups: 1, bias: true, padding_mode: "zeros", device: null, dtype: null},
                inputShape: "[In, L]",
                outputShape: "[Out, L']",
            },
            {
                type: "Conv2d",
                label: "Conv2D",
                iconName: "Layers",
                color: "text-green-600",
                params: {in_channels: 3, out_channels: 64, kernel_size: 3, stride: 1, padding: 0, dilation: 1, groups: 1, bias: true, padding_mode: "zeros", device: null, dtype: null},
                inputShape: "[In, H, W]",
                outputShape: "[Out, H', W']",
            },
            {
                type: "Conv3d",
                label: "Conv3D",
                iconName: "Layers",
                color: "text-yellow-600",
                params: {in_channels: 3, out_channels: 64, kernel_size: 3},
                inputShape: "[In, D, H, W]",
                outputShape: "[Out, D', H', W']",
            },
        ],
    },
    {
        category: "Polling Layers",
        layers: [
            {
                type: "MaxPool1d",
                label: "MaxPool1D",
                iconName: "Layers",
                color: "text-blue-600",
                params: {kernel_size: 2, stride: null, padding: 0, dilation: 1, return_indices: false, ceil_mode: false},
                inputShape: "[C, L]",
                outputShape: "[C, L']",
            },
            {
                type: "MaxPool2d",
                label: "MaxPool2D",
                iconName: "Layers",
                color: "text-green-600",
                params: {kernel_size: 2, stride: null, padding: 0, dilation: 1, return_indices: false, ceil_mode: false},
                inputShape: "[C, H, W]",
                outputShape: "[C, H', W']",
            },
            {
                type: "MaxPool3d",
                label: "MaxPool3D",
                iconName: "Layers",
                color: "text-yellow-600",
                params: {kernel_size: 2, stride: 2, padding: 0, dilation: 1, return_indices: false, ceil_mode: false},
                inputShape: "[C, D, H, W]",
                outputShape: "[C, D', H', W']",
            },
        ],
    },
    {
        category: "Activation Functions",
        layers: [
            {
                type: "ReLU",
                label: "ReLU",
                iconName: "Zap",
                color: "text-red-600",
                params: {inplace: false},
                inputShape: "[C]",
                outputShape: "[C]",
            },
            {
                type: "Sigmoid",
                label: "Sigmoid",
                iconName: "Zap",
                color: "text-pink-600",
                params: {},
                inputShape: "[C]",
                outputShape: "[C]",
            },
            {
                type: "Softmax",
                label: "Softmax",
                iconName: "Zap",
                color: "text-indigo-600",
                params: {dim: null},
                inputShape: "[C]",
                outputShape: "[C]",
            },
            {
                type: "LogSoftmax",
                label: "LogSoftmax",
                iconName: "Zap",
                color: "text-indigo-600",
                params: {dim: null},
                inputShape: "[C]",
                outputShape: "[C]",
            },
        ],
    },
    {
        category: "Utility Functions",
        layers: [
            {
                type: "Flatten",
                label: "Flatten",
                iconName: "Layers",
                color: "text-blue-600",
                params: {start_dim: 1, end_dim: -1},
                inputShape: "[C, H, W]",
                outputShape: "[C * H * W]",
            },
        ],
    },
]
